<form
    action="<?php echo $action ?>"
    <?php if($view->form_name): ?>
    id="<?php echo "magic-form-{$view->form_name}"; ?>"
    <?php endif; ?>
    class="magic_form <?php echo implode(" ", $classes); ?>"
    method="POST"
    enctype="multipart/form-data"
    >
  <input type="hidden" name="magic_form_id" value="<?php echo $form_id ?>"/>
  <?php foreach ($form_rows as $form_row): ?>
    <?php
    /* @var $form_row magic_form_item */
    $form_row->set_scope($view->scope);
    echo $form_row->__toString();
    ?>
  <?php endforeach; ?>
  <div class="clear"></div>
</form>