<?php

require_once("lib/magic_form.inc");
require_once("lib/magic_form_item.inc");
require_once("lib/magic_form_field.inc");
require_once("lib/magic_form_field_button.inc");
require_once("lib/magic_form_field_datatable.inc");
require_once("lib/magic_form_field_file.inc");
require_once("lib/magic_form_field_multi.inc");
require_once("lib/magic_form_field_radio.inc");
require_once("lib/magic_form_field_select.inc");
require_once("lib/magic_form_field_submit.inc");
require_once("lib/magic_form_field_text.inc");
require_once("lib/magic_form_field_textarea.inc");

// Depend on magic_form_field_text being loaded already
require_once("lib/magic_form_field_date.inc");
require_once("lib/magic_form_field_hidden.inc");
require_once("lib/magic_form_field_number.inc");

// Groups support
require_once("lib/magic_form_group.inc");

// Magic Clojure.
require_once("lib/magic_serialisable_clojure.inc");

define("MAGIC_FORMS_MAX_ACTIVE_FORMS", 5);
define("MAGIC_FORMS_DEBUG", TRUE);
define("MAGIC_FORMS_SERIALISED_MAX_BYTES", 5000000); // 500KB

/**
 * Initialisation
 * Do not remove hook_page_alter(), its used to detect magic_forms installation presence & do the magic that makes
 * magic_forms magical.
 */
function magic_forms_page_alter()
{
   if (isset($_SESSION['magic_forms'])) {

      // If we're in debug mode...
      if(MAGIC_FORMS_DEBUG){

        // Unserialise the serialised content for display
        $forms_unserialised = array();
        foreach($_SESSION['magic_forms'] as $i => $form){
          $form_unserialised = $form;
          $form_unserialised['form'] = unserialize($form_unserialised['form']);
          $serialised_data = serialize($form_unserialised);
          $forms_unserialised[$i . " " . strlen($serialised_data) . " bytes"] = $form_unserialised;
        }

        // Reserialise it for a memory total
        $serialised_data = serialize($forms_unserialised);
        drupal_set_message("Magic Forms Memory: " . strlen($serialised_data) . " bytes. (" . ((100/MAGIC_FORMS_SERIALISED_MAX_BYTES) * strlen($serialised_data)) . "% of MAGIC_FORMS_SERIALISED_MAX_BYTES)");

        // If serialised data exceeds 1MB, somethings gone wrong.
        if(strlen($serialised_data) >= MAGIC_FORMS_SERIALISED_MAX_BYTES){
          drupal_set_message("Purging serialised data, exceeded " . MAGIC_FORMS_SERIALISED_MAX_BYTES . " bytes");
        }
        krumo($forms_unserialised);
      }
      if (isset($_REQUEST['magic_form_id'])) {
          magic_form::remove_other_forms($_REQUEST['magic_form_id']);
          magic_form::process($_REQUEST['magic_form_id']);
      }
      magic_form::cleanup_expired_forms();
    }
}

/**
 * Crunch through a view
 *
 * @param string $file File of the template to call.
 * @param array|object $view Optional view array.
 *
 * @return string
 */
function magic_forms_template_view($file, $view = null)
{
    $file = DRUPAL_ROOT . "/" . drupal_get_path('module', 'magic_forms') . '/templates/' . $file;
    if (!file_exists($file)) {
        return "Cannot find {$file}";
    }
    extract((array)$view);
    ob_start();
    require($file);
    $markup = ob_get_contents();
    ob_end_clean();
    return $markup;
}

/**
 * CSS class mangler
 * Mangle a string like "Layout Magic Doodah" to "layout-magic-doodah" for use as a CSS class
 *
 * @param string $text text string to mangle
 *
 * @return string css class
 */
function magic_forms_mangle_to_css_class($text)
{
    $text = str_replace(" ", "-", $text);
    $text = preg_replace("/[^a-zA-Z0-9-]+/", "", $text);
    $text = strtolower($text);
    return $text;
}