<div
  class="form-group form_checkbox_multi field-<?php echo magic_forms_mangle_to_css_class($field->get_name()); ?> <?php echo $field->get_classes('form_row_'); ?>">
  <?php require("form.label.phtml"); ?>
  <?php if (count($field->get_options()) > 0): ?>
    <div class="btn-group multiswitch_group" data-toggle="buttons">
      <?php foreach ($field->get_options() as $key => $option_label): ?>


        <label class="multiswitch_group_option btn btn-primary <?php if ($key == $field->get_value()): ?>active" <?php endif; ?>">
          <input type="radio"
                 name="<?php echo $field->get_name(); ?>"
                 autocomplete="off"
                 value="<?php echo $field->get_value(); ?>"
                <?php if ($key == $field->get_value()): ?>
                checked="checked"
                <?php endif; ?>
            > <?php echo $option_label; ?>
        </label>

      <?php endforeach; ?>
    </div>
  <?php endif; ?>
  <?php require "form.errors.phtml"; ?>
</div>