<div
  class="form-group form_button field-<?php echo magic_forms_mangle_to_css_class($field->get_name()); ?> <?php echo $field->get_classes('form_row_'); ?>">

  <input
    type="button"
    name="<?php echo $field->get_name(); ?>"
    value="<?php echo $field->get_label() ?>"
    class="form-control <?php echo $field->get_classes(); ?>"
    <?php if ($field->is_disabled()): ?>
      disabled="disabled"
    <?php endif; ?>
    <?php echo $field->get_attributes(); ?>
    />
  <?php require "form.errors.phtml"; ?>

</div>