<div
  class="form-group form_input form-range field-<?php echo magic_forms_mangle_to_css_class($field->get_name()); ?> <?php echo $field->get_classes('form_row_'); ?>  <?php if (!$field->get_label()) { echo 'hasnolabel'; } ?>">
  <?php require("form.label.phtml"); ?>

  <div class="range_group">

    <input
      type="text" id="<?php echo magic_forms_mangle_to_css_class($field->get_name()); ?>_<?php echo uniqid(); ?>"
      class="span2 field-range-slider field-slider-<?php echo magic_forms_mangle_to_css_class($field->get_name()); ?>-input"
      value="<?php if($field->get_value()) { echo $field->get_value(); } else { if ($field->get_min()) { echo $field->get_min(); }  else { $incrementminmax = $field->get_increments(); echo reset($incrementminmax); } } ?>"
      data-slider="true"
      <?php if (is_array($field->get_increments())) { ?>
        data-slider-values="<?php echo implode(',', $field->get_increments()); ?>"
      <?php } else { ?>
        data-slider-range="<?php echo $field->get_min(); ?>,<?php echo $field->get_max(); ?>"
        data-slider-step="<?php echo $field->get_step(); ?>"
      <?php } ?>
      data-slider-unit="<?php echo $field->get_unit(); ?>"
      data-slider-snap="true"
      data-slider-highlight="true"
      data-slider-equal-steps="<?php echo (is_array($field->get_increments()) ? 'true' : 'false'); ?>"
      data-slider-tooltip="<?php echo ($field->get_option('show_tooltip') ? 'true' : 'false'); ?>"
      <?php if ($field->is_disabled()): ?>
        data-slider-disabled="disabled"
        readonly
      <?php endif; ?>
      <?php echo $field->get_attributes(); ?>
      />



   <div class="<?php echo magic_forms_mangle_to_css_class($field->get_name()); ?>_value"></div>
    <?php if ($field->get_option('show_minmax')) {  ?>
    <div class="slide_options slide_minmax">
      <?php if (!$field->get_min() && !$field->get_max()) { $incrementminmax = array(); $incrementminmax = $field->get_increments(); ?>

        <div class="min"><?php echo reset($incrementminmax); ?><?php echo ($field->get_unit() ? $field->get_unit() : ''); ?></div> <div class="max"><?php echo end($incrementminmax); ?><?php echo ($field->get_unit() ? $field->get_unit() : ''); ?></div>
      <?php } else { ?>
        <div class="min"><?php echo $field->get_min(); ?><?php echo ($field->get_unit() ? $field->get_unit() : ''); ?></div> <div class="max"><?php echo $field->get_max(); ?><?php echo ($field->get_unit() ? $field->get_unit() : ''); ?></div>
      <?php } ?>
    </div>


  <?php } else if ($field->get_option('show_increments')) { ?>
  <div id="<?php echo magic_forms_mangle_to_css_class($field->get_name()); ?>_options" class="slide_<?php echo magic_forms_mangle_to_css_class($field->get_name()); ?>_options slide_options">
    <?php
    if ($field->get_increments()) {
      $width = 100 / count($field->get_increments());
      foreach ($field->get_increments() as $increment) {
        //echo '<div class="option_'.$increment.'" style="width:'.$width.'%">'.$increment.''.($field->get_unit() ? $field->get_unit() : '').'</div>';
        echo '<div>'.$increment.''.($field->get_unit() ? $field->get_unit() : '').'</div>
        ';
      }
    }
    ?>
  </div>
  <?php } ?>
  </div>
  <?php require "form.errors.phtml"; ?>
</div>
