<div
  class="form-group form_textarea field-<?php echo magic_forms_mangle_to_css_class($field->get_name()); ?> <?php echo $field->get_classes('form_row_'); ?>">
  <?php require("form.label.phtml"); ?>
  <textarea
    id="<?php echo magic_forms_mangle_to_css_class($field->get_name()); ?>"
    type="text"
    name="<?php echo $field->get_name(); ?>"
    class="form-control <?php echo $field->get_classes(); ?>"
    rows="10"
    <?php if ($field->is_disabled()): ?>
      readonly
    <?php endif; ?>
    <?php echo $field->get_attributes(); ?>
    ><?php echo $field->get_value() ?></textarea>
  <?php require "form.errors.phtml"; ?>
</div>