<div class="form-group form_file field-<?php echo magic_forms_mangle_to_css_class($field->get_name()); ?> <?php echo $field->get_classes('form_row_'); ?>">
  <?php require("form.label.phtml"); ?>
  <input
    id="<?php echo magic_forms_mangle_to_css_class($field->get_name()); ?>"
    type="file"
    name="<?php echo $field->get_name(); ?>"
    class="<?php echo $field->get_classes(); ?>"
    <?php if ($field->is_disabled()): ?>
      disabled="disabled"
    <?php endif; ?>
    />
  <?php require "form.errors.phtml"; ?>
</div>