<div class="form_row field-<?php echo magic_forms_mangle_to_css_class($field->get_name()); ?>">

  <input
    type="submit"
    id="<?php echo $field->get_name(); ?>"
    name="<?php echo $field->get_name(); ?>"
    value="<?php echo $field->get_label() ?>"
    <?php if ($field->is_disabled()): ?>
      disabled="disabled"
    <?php endif; ?>
    />

  <div class="clear"></div>
</div>