<div class="form_row">

  <?php require("form.label.phtml"); ?>

  <select
    name="<?php echo $field->get_name(); ?>"
    id="<?php echo magic_forms_mangle_to_css_class($field->get_name()); ?>"
    >
    <?php if($field->null_value_allowed()): ?>
      <option value=""> --- </option>
    <?php endif; ?>
    <?php if (count($field->get_options()) > 0): ?>
      <?php foreach ($field->get_options() as $key => $option_label): ?>
        <option value="<?php echo $key; ?>"><?php echo $option_label; ?></option>
      <?php endforeach; ?>
    <?php endif; ?>
  </select>

  <div class="clear"></div>
</div>