<div class="form_group field-<?php echo magic_forms_mangle_to_css_class($field->get_name()); ?>">
  <?php if (strlen($field->get_group_name()) > 0): ?>
    <h3><?php echo $field->get_group_name(); ?></h3>
  <?php endif; ?>

  <?php if(count($field->get_fields()) > 0): ?>
    <?php foreach ($field->get_fields() as $field): ?>
      <?php echo $field; ?>
    <?php endforeach; ?>
  <?php endif; ?>
</div>