<?php require("form.label.phtml"); ?>

<table>
  <thead>
    <tr>
      <?php foreach($field->get_headings() as $heading): ?>
        <td><?php echo $heading; ?></td>
      <?php endforeach; ?>
    </tr>
  </thead>
  <tbody>
    <?php foreach($field->get_rows() as $row): ?>
      <tr>
        <?php foreach($row as $cell_name => $cell_value): ?>
          <td><?php echo $cell_value; ?></td>
        <?php endforeach?>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>