<div class="form_row field-<?php echo magic_forms_mangle_to_css_class($field->get_name()); ?>">

  <input
    type="button"
    name="<?php echo $field->get_name(); ?>"
    value="<?php echo $field->get_label() ?>"
    class="<?php $field->get_classes(); ?>"
    <?php if ($field->is_disabled()): ?>
      disabled="disabled"
    <?php endif; ?>
    />

  <div class="clear"></div>
</div>